//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezha90
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Класс номера.
    /// </summary>
    // *** Start programmer edit section *** (КлассНомера CustomAttributes)

    // *** End programmer edit section *** (КлассНомера CustomAttributes)
    public enum КлассНомера
    {
        
        // *** Start programmer edit section *** (КлассНомера.4 CustomAttributes)

        // *** End programmer edit section *** (КлассНомера.4 CustomAttributes)
        [Caption("Эконом")]
        4,
        
        // *** Start programmer edit section *** (КлассНомера.2 CustomAttributes)

        // *** End programmer edit section *** (КлассНомера.2 CustomAttributes)
        [Caption("Комфорт")]
        2,
        
        // *** Start programmer edit section *** (КлассНомера.1 CustomAttributes)

        // *** End programmer edit section *** (КлассНомера.1 CustomAttributes)
        [Caption("Бизнес")]
        1,
        
        // *** Start programmer edit section *** (КлассНомера.3 CustomAttributes)

        // *** End programmer edit section *** (КлассНомера.3 CustomAttributes)
        [Caption("Президентский")]
        3,
    }
}
