//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezha90
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Напитки.
    /// </summary>
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НапиткиE", new string[] {
            "КодНапитка as \'Код напитка\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    [AssociatedDetailViewAttribute("НапиткиE", "СоставНапитков", "СоставНапитковE", true, "", "Состав напитков", true, new string[] {
            ""})]
    [View("НапиткиL", new string[] {
            "КодНапитка as \'Код напитка\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    public class Напитки : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодНапитка;
        
        private string fНаименование;
        
        private double fСтоимость;
        
        private IIS.Serezha90.DetailArrayOfСоставНапитков fСоставНапитков;
        
        /// <summary>
        /// КодНапитка.
        /// </summary>
        // *** Start programmer edit section *** (Напитки.КодНапитка CustomAttributes)

        // *** End programmer edit section *** (Напитки.КодНапитка CustomAttributes)
        public virtual int КодНапитка
        {
            get
            {
                // *** Start programmer edit section *** (Напитки.КодНапитка Get start)

                // *** End programmer edit section *** (Напитки.КодНапитка Get start)
                int result = this.fКодНапитка;
                // *** Start programmer edit section *** (Напитки.КодНапитка Get end)

                // *** End programmer edit section *** (Напитки.КодНапитка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Напитки.КодНапитка Set start)

                // *** End programmer edit section *** (Напитки.КодНапитка Set start)
                this.fКодНапитка = value;
                // *** Start programmer edit section *** (Напитки.КодНапитка Set end)

                // *** End programmer edit section *** (Напитки.КодНапитка Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Напитки.Наименование CustomAttributes)

        // *** End programmer edit section *** (Напитки.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Напитки.Наименование Get start)

                // *** End programmer edit section *** (Напитки.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Напитки.Наименование Get end)

                // *** End programmer edit section *** (Напитки.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Напитки.Наименование Set start)

                // *** End programmer edit section *** (Напитки.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Напитки.Наименование Set end)

                // *** End programmer edit section *** (Напитки.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Напитки.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Напитки.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Напитки.Стоимость Get start)

                // *** End programmer edit section *** (Напитки.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (Напитки.Стоимость Get end)

                // *** End programmer edit section *** (Напитки.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Напитки.Стоимость Set start)

                // *** End programmer edit section *** (Напитки.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Напитки.Стоимость Set end)

                // *** End programmer edit section *** (Напитки.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Напитки.
        /// </summary>
        // *** Start programmer edit section *** (Напитки.СоставНапитков CustomAttributes)

        // *** End programmer edit section *** (Напитки.СоставНапитков CustomAttributes)
        public virtual IIS.Serezha90.DetailArrayOfСоставНапитков СоставНапитков
        {
            get
            {
                // *** Start programmer edit section *** (Напитки.СоставНапитков Get start)

                // *** End programmer edit section *** (Напитки.СоставНапитков Get start)
                if ((this.fСоставНапитков == null))
                {
                    this.fСоставНапитков = new IIS.Serezha90.DetailArrayOfСоставНапитков(this);
                }
                IIS.Serezha90.DetailArrayOfСоставНапитков result = this.fСоставНапитков;
                // *** Start programmer edit section *** (Напитки.СоставНапитков Get end)

                // *** End programmer edit section *** (Напитки.СоставНапитков Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Напитки.СоставНапитков Set start)

                // *** End programmer edit section *** (Напитки.СоставНапитков Set start)
                this.fСоставНапитков = value;
                // *** Start programmer edit section *** (Напитки.СоставНапитков Set end)

                // *** End programmer edit section *** (Напитки.СоставНапитков Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НапиткиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НапиткиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НапиткиE", typeof(IIS.Serezha90.Напитки));
                }
            }
            
            /// <summary>
            /// "НапиткиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НапиткиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НапиткиL", typeof(IIS.Serezha90.Напитки));
                }
            }
        }
    }
}
