//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezha90
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номера.
    /// </summary>
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НомераE", new string[] {
            "НомерКомнаты as \'Номер комнаты\'",
            "ТипНомера as \'Тип номера\'"})]
    [View("НомераL", new string[] {
            "НомерКомнаты as \'Номер комнаты\'",
            "ТипНомера as \'Тип номера\'"})]
    public class Номера : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКомнаты;
        
        private IIS.Serezha90.КлассНомера fТипНомера;
        
        /// <summary>
        /// НомерКомнаты.
        /// </summary>
        // *** Start programmer edit section *** (Номера.НомерКомнаты CustomAttributes)

        // *** End programmer edit section *** (Номера.НомерКомнаты CustomAttributes)
        public virtual int НомерКомнаты
        {
            get
            {
                // *** Start programmer edit section *** (Номера.НомерКомнаты Get start)

                // *** End programmer edit section *** (Номера.НомерКомнаты Get start)
                int result = this.fНомерКомнаты;
                // *** Start programmer edit section *** (Номера.НомерКомнаты Get end)

                // *** End programmer edit section *** (Номера.НомерКомнаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номера.НомерКомнаты Set start)

                // *** End programmer edit section *** (Номера.НомерКомнаты Set start)
                this.fНомерКомнаты = value;
                // *** Start programmer edit section *** (Номера.НомерКомнаты Set end)

                // *** End programmer edit section *** (Номера.НомерКомнаты Set end)
            }
        }
        
        /// <summary>
        /// ТипНомера.
        /// </summary>
        // *** Start programmer edit section *** (Номера.ТипНомера CustomAttributes)

        // *** End programmer edit section *** (Номера.ТипНомера CustomAttributes)
        public virtual IIS.Serezha90.КлассНомера ТипНомера
        {
            get
            {
                // *** Start programmer edit section *** (Номера.ТипНомера Get start)

                // *** End programmer edit section *** (Номера.ТипНомера Get start)
                IIS.Serezha90.КлассНомера result = this.fТипНомера;
                // *** Start programmer edit section *** (Номера.ТипНомера Get end)

                // *** End programmer edit section *** (Номера.ТипНомера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номера.ТипНомера Set start)

                // *** End programmer edit section *** (Номера.ТипНомера Set start)
                this.fТипНомера = value;
                // *** Start programmer edit section *** (Номера.ТипНомера Set end)

                // *** End programmer edit section *** (Номера.ТипНомера Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НомераE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НомераE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НомераE", typeof(IIS.Serezha90.Номера));
                }
            }
            
            /// <summary>
            /// "НомераL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НомераL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НомераL", typeof(IIS.Serezha90.Номера));
                }
            }
        }
    }
}
