//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezha90
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр.
    /// </summary>
    // *** Start programmer edit section *** (Регистр CustomAttributes)

    // *** End programmer edit section *** (Регистр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрE", new string[] {
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "Сумма as \'Сумма\'",
            "КодЗазака as \'Код зазака\'",
            "Заказы as \'Заказы\'",
            "Заказы.Время as \'Время\'"}, Hidden=new string[] {
            "Заказы.Время"})]
    [MasterViewDefineAttribute("РегистрE", "Заказы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Время")]
    [View("РегистрL", new string[] {
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "Сумма as \'Сумма\'",
            "КодЗазака as \'Код зазака\'",
            "Заказы.Время as \'Время\'"})]
    public class Регистр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private string fВремя;
        
        private double fСумма;
        
        private int fКодЗазака;
        
        private IIS.Serezha90.Заказы fЗаказы;
        
        // *** Start programmer edit section *** (Регистр CustomMembers)

        // *** End programmer edit section *** (Регистр CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Время CustomAttributes)

        // *** End programmer edit section *** (Регистр.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Время Get start)

                // *** End programmer edit section *** (Регистр.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (Регистр.Время Get end)

                // *** End programmer edit section *** (Регистр.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Время Set start)

                // *** End programmer edit section *** (Регистр.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Регистр.Время Set end)

                // *** End programmer edit section *** (Регистр.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Дата CustomAttributes)

        // *** End programmer edit section *** (Регистр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Дата Get start)

                // *** End programmer edit section *** (Регистр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Регистр.Дата Get end)

                // *** End programmer edit section *** (Регистр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Дата Set start)

                // *** End programmer edit section *** (Регистр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Регистр.Дата Set end)

                // *** End programmer edit section *** (Регистр.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗазака.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.КодЗазака CustomAttributes)

        // *** End programmer edit section *** (Регистр.КодЗазака CustomAttributes)
        public virtual int КодЗазака
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.КодЗазака Get start)

                // *** End programmer edit section *** (Регистр.КодЗазака Get start)
                int result = this.fКодЗазака;
                // *** Start programmer edit section *** (Регистр.КодЗазака Get end)

                // *** End programmer edit section *** (Регистр.КодЗазака Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.КодЗазака Set start)

                // *** End programmer edit section *** (Регистр.КодЗазака Set start)
                this.fКодЗазака = value;
                // *** Start programmer edit section *** (Регистр.КодЗазака Set end)

                // *** End programmer edit section *** (Регистр.КодЗазака Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Сумма CustomAttributes)

        // *** End programmer edit section *** (Регистр.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Сумма Get start)

                // *** End programmer edit section *** (Регистр.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Регистр.Сумма Get end)

                // *** End programmer edit section *** (Регистр.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Сумма Set start)

                // *** End programmer edit section *** (Регистр.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Регистр.Сумма Set end)

                // *** End programmer edit section *** (Регистр.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Регистр.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Заказы CustomAttributes)

        // *** End programmer edit section *** (Регистр.Заказы CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказы"})]
        [NotNull()]
        public virtual IIS.Serezha90.Заказы Заказы
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Заказы Get start)

                // *** End programmer edit section *** (Регистр.Заказы Get start)
                IIS.Serezha90.Заказы result = this.fЗаказы;
                // *** Start programmer edit section *** (Регистр.Заказы Get end)

                // *** End programmer edit section *** (Регистр.Заказы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Заказы Set start)

                // *** End programmer edit section *** (Регистр.Заказы Set start)
                this.fЗаказы = value;
                // *** Start programmer edit section *** (Регистр.Заказы Set end)

                // *** End programmer edit section *** (Регистр.Заказы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрE", typeof(IIS.Serezha90.Регистр));
                }
            }
            
            /// <summary>
            /// "РегистрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрL", typeof(IIS.Serezha90.Регистр));
                }
            }
        }
    }
}
