//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezha90
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав блюда.
    /// </summary>
    [Caption("Состав блюда")]
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставБлюдаE", new string[] {
            "Количество as \'Количество\'",
            "Единицы as \'Единицы\'",
            "Продукты as \'Продукты\'",
            "Продукты.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Продукты.Наименование"})]
    [MasterViewDefineAttribute("СоставБлюдаE", "Продукты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СоставБлюда : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Serezha90.Единицы fЕдиницы;
        
        private IIS.Serezha90.Продукты fПродукты;
        
        private IIS.Serezha90.Блюда fБлюда;
        
        /// <summary>
        /// Единицы.
        /// </summary>
        // *** Start programmer edit section *** (СоставБлюда.Единицы CustomAttributes)

        // *** End programmer edit section *** (СоставБлюда.Единицы CustomAttributes)
        public virtual IIS.Serezha90.Единицы Единицы
        {
            get
            {
                // *** Start programmer edit section *** (СоставБлюда.Единицы Get start)

                // *** End programmer edit section *** (СоставБлюда.Единицы Get start)
                IIS.Serezha90.Единицы result = this.fЕдиницы;
                // *** Start programmer edit section *** (СоставБлюда.Единицы Get end)

                // *** End programmer edit section *** (СоставБлюда.Единицы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставБлюда.Единицы Set start)

                // *** End programmer edit section *** (СоставБлюда.Единицы Set start)
                this.fЕдиницы = value;
                // *** Start programmer edit section *** (СоставБлюда.Единицы Set end)

                // *** End programmer edit section *** (СоставБлюда.Единицы Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СоставБлюда.Количество CustomAttributes)

        // *** End programmer edit section *** (СоставБлюда.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СоставБлюда.Количество Get start)

                // *** End programmer edit section *** (СоставБлюда.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СоставБлюда.Количество Get end)

                // *** End programmer edit section *** (СоставБлюда.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставБлюда.Количество Set start)

                // *** End programmer edit section *** (СоставБлюда.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СоставБлюда.Количество Set end)

                // *** End programmer edit section *** (СоставБлюда.Количество Set end)
            }
        }
        
        /// <summary>
        /// Состав блюда.
        /// </summary>
        // *** Start programmer edit section *** (СоставБлюда.Продукты CustomAttributes)

        // *** End programmer edit section *** (СоставБлюда.Продукты CustomAttributes)
        [PropertyStorage(new string[] {
                "Продукты"})]
        [NotNull()]
        public virtual IIS.Serezha90.Продукты Продукты
        {
            get
            {
                // *** Start programmer edit section *** (СоставБлюда.Продукты Get start)

                // *** End programmer edit section *** (СоставБлюда.Продукты Get start)
                IIS.Serezha90.Продукты result = this.fПродукты;
                // *** Start programmer edit section *** (СоставБлюда.Продукты Get end)

                // *** End programmer edit section *** (СоставБлюда.Продукты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставБлюда.Продукты Set start)

                // *** End programmer edit section *** (СоставБлюда.Продукты Set start)
                this.fПродукты = value;
                // *** Start programmer edit section *** (СоставБлюда.Продукты Set end)

                // *** End programmer edit section *** (СоставБлюда.Продукты Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Serezha90.Блюда.
        /// </summary>
        // *** Start programmer edit section *** (СоставБлюда.Блюда CustomAttributes)

        // *** End programmer edit section *** (СоставБлюда.Блюда CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Блюда"})]
        public virtual IIS.Serezha90.Блюда Блюда
        {
            get
            {
                // *** Start programmer edit section *** (СоставБлюда.Блюда Get start)

                // *** End programmer edit section *** (СоставБлюда.Блюда Get start)
                IIS.Serezha90.Блюда result = this.fБлюда;
                // *** Start programmer edit section *** (СоставБлюда.Блюда Get end)

                // *** End programmer edit section *** (СоставБлюда.Блюда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставБлюда.Блюда Set start)

                // *** End programmer edit section *** (СоставБлюда.Блюда Set start)
                this.fБлюда = value;
                // *** Start programmer edit section *** (СоставБлюда.Блюда Set end)

                // *** End programmer edit section *** (СоставБлюда.Блюда Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставБлюдаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставБлюдаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставБлюдаE", typeof(IIS.Serezha90.СоставБлюда));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставБлюда.
    /// </summary>
    public class DetailArrayOfСоставБлюда : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Serezha90.DetailArrayOfСоставБлюда members)

        // *** End programmer edit section *** (IIS.Serezha90.DetailArrayOfСоставБлюда members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставБлюда by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставБлюда.
        /// </summary>
        public DetailArrayOfСоставБлюда(IIS.Serezha90.Блюда fБлюда) : 
                base(typeof(СоставБлюда), ((ICSSoft.STORMNET.DataObject)(fБлюда)))
        {
        }
        
        public IIS.Serezha90.СоставБлюда this[int index]
        {
            get
            {
                return ((IIS.Serezha90.СоставБлюда)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Serezha90.СоставБлюда dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
